const TUYA_EMAIL_KEY = 'TUYA_EMAIL';
const TUYA_PASSWORD_KEY = 'TUYA_PASSWORD';
const TUYA_REGION_KEY = 'TUYA_REGION';
const TUYA_REGIONS = {
  CN: 'cn',
  EU: 'eu',
  US: 'us',
};

const DEVICE_SERVICE_ID = 'tuya';
const DEVICE_EXTERNAL_ID_BASE = 'tuya';
const DEVICE_IP_ADDRESS = 'IP_ADDRESS';
const DEVICE_FIRMWARE = 'FIRMWARE';

module.exports = {
  TUYA_EMAIL_KEY,
  TUYA_PASSWORD_KEY,
  TUYA_REGION_KEY,
  TUYA_REGIONS,
  DEVICE_SERVICE_ID,
  DEVICE_EXTERNAL_ID_BASE,
  DEVICE_IP_ADDRESS,
  DEVICE_FIRMWARE,
};
